### ISSUE TITLE
suggestion: add openapi utilities (or add in examples)

### ISSUE THREAD

**Issue by jkone27** [Lanayx/Oxpecker#11]
Awesome library, not using your lib in this example, but was just thinking maybe also it could benefid from some quick functional openapi utility functions?

would be greate if at leat all "extension methods" could be instead functional pipelines..

```fsharp
|> withName ""
|> withOpenApi
```

<img width="1169" alt="image" src="https://github.com/Lanayx/Oxpecker/assets/10419217/84be1c04-4179-4d61-8ce5-6046137bd452">

seems openapi reg is not very "functional" but ofc it should work fine with this on endpoint routing (adding 2 packages as dependencies

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-8.0

**Comment by Lanayx** [comment]
Thank you for suggestion! I've actually thought about openApi, you can check it out here: https://github.com/Lanayx/Oxpecker/blob/openApi/examples/OpenApi/Program.fs (just adding 2 packages doesn't work, so manual api description is needed).  However I stopped there, because I figured out that the proper way would be to generate server stub base on schema (similar to https://github.com/Szer/GiraffeGenerator) and not the opposite. So, I'm not sure if I need to merge openApi example into develop branch, since it looks quit hacky.

**Comment by Lanayx** [comment]
An update :) As soon as it appeared to be possible to reuse built-in OpenApi generation with low effort it was added as Oxpecker.OpenApi package. I still think that schema-first approach works better for big projects, but for small ones with a tight time schedule ability to quickly generate is indeed useful, hence the package was born. 
With that I'm closing current ticket, any other issues of the implementation can be raised in separate tickets.
