### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by clement128** [Lanayx/Oxpecker#13]
Hi, thanks for the great works.

do you think it would be better to add release notes (or changelog)? Or where can I view the release history?

**Comment by Lanayx** [comment]
Hi! Thanks for asking. Indeed, having release notes can be convenient for active users who want to understand what have changed from release to release. However this also implies more **rare** releases, since writing a release notes on every small change is pretty depressing job. While Oxpecker libraries are all now at 0.x versions and many small changes/refactorings are done - I wouldn't commit to that. But once Oxpecker gets more adoption and reaches 1.0 I think that I have to do more beautiful releases anyway.
Right now you can find all releases with short descriptions here: https://github.com/Lanayx/Oxpecker/tags or on Nuget

**Comment by Lanayx** [comment]
First release done, I'll try to keep it going :)
