### ISSUE TITLE
Add minimal getting started doc in Readme

### ISSUE THREAD

**Issue by jkone27** [Lanayx/Oxpecker#23]
suggestion, add minimal getting started code docs in readme, 
so people can quickly get started without diving deep into other docs or tests or samples

e.g. in fsx, is there a way to make configuration more fluent, like Saturn or Falco? or maybe instead of CE using some adapter functions so configuration can be chained simply with `|>` 

```fsharp
#load "runtime-scripts/Microsoft.AspNetCore.App-latest-8.fsx"
#r "nuget: Oxpecker"

open Microsoft.AspNetCore.Builder
open Microsoft.Extensions.DependencyInjection
open Oxpecker

let endpoints = [
    route "/hello" ("Hello World!" |> text)
    route "/hello-json" ("""{ "Hello": "World!" }""" |> json)
]

let configure (builder: WebApplicationBuilder) =
    builder.Services.AddRouting().AddOxpecker() |> ignore
    builder.Build()

let configureApp (app: WebApplication) =
    app.UseRouting().UseOxpecker(endpoints) |> ignore
    app

let webApp = 
    WebApplication.CreateBuilder()
    |> configure
    |> configureApp

webApp.Run()
```

**Comment by Lanayx** [comment]
@jkone27 Will reference to the Empty example work?
https://github.com/Lanayx/Oxpecker/blob/develop/examples/Empty/Program.fs

**Comment by jkone27** [comment]
sure, i posted an example also for openapi that doesnt seem to work, if u want to try it. opened separate issue, glad to contribute to docs sure

**Comment by Lanayx** [comment]
I've added a documentation change, also wanted to comment on this

`e.g. in fsx, is there a way to make configuration more fluent, like Saturn or Falco?`

You won't believe, but one of the main reasons I created Oxpecker instead of going with Falco or Saturn is that I didn't like their builders approach :) And it seems to be the right choice, since as far as I know recently Falco got rid of builders as well (even though it was a breaking change).

**Comment by Lanayx** [comment]
Closing as starting doc was updated, any work regarding script support should relate to #10

**Comment by Thorium** [comment]
> is there a way to make configuration more fluent, like Saturn or Falco?

These C#-based aspnetcore/owin pipelines are using state-monad to represent the application pipeline (State to Pair<State, Content> (see @rebcabin old videos e.g. https://www.youtube.com/watch?v=XxzzJiXHOJs ). In the application pipeline, the "state" is the context that is passed around (and specifically the "response" part of that context, that is modified).

Sadly, the C# guys selected the wrong monad. The order of these ASP.NET Core/OWIN components does matter, where the state-monad is expecting that the order doesn't matter. So, for example, you definitely want to put your authentication component before the static-files component, and not the other way round. As the order does matter,  they should have selected the index monad instead of the state monad.

I do like the F# builders, like Saturn has (if the intellisense worked better). 
I think they could have some value in Oxpecker, but I think they would have more value if the F#-builders would have separate classes (or DUs) to extend the validity of the builder/state, same way I've defined [here](https://github.com/CompositionalIT/farmer/issues/693#issue-941966641).

**Comment by Lanayx** [comment]
Linking another discussion about builders

**Comment by Thorium** [comment]
Thanks, I was lopking more the aspnetcore server-side CE because currently I fail to understand what should be configured in the "services" and what in the "application", so I end-up doing things in both, twice, just to be on the safe side.

**Comment by Lanayx** [comment]
Oops, I was really talking about those "services" and "application" CE in that thread and didn't realize the meaning of words "CE for routing", since Oxpecker is a CE for routing. Will rename it
