### ISSUE TITLE
openapi spec autoconfigure for endpoints

### ISSUE THREAD

**Issue by jkone27** [Lanayx/Oxpecker#24]
first and foremost thank you so much for this awesome project :) 

is there a way to add openapi spec with reflection instead of having to manually configure endpoints? 

https://github.com/Lanayx/Oxpecker/blob/51d8e2db9e30f6817c7e8ffafc7cc22228b385a3/src/Oxpecker.OpenApi/README.md

the whole thing of swagger/swashbuckle is also to allow contract driven development but by writing code first, openapi should be autogenerated by code, so that devs can just implement endpoints and a working contract is generated based on those and endpoint metadata..

https://github.com/pimbrouwers/Falco/issues/49

i see this package is doing something similar to this: oki
https://gist.github.com/jkone27/953d4c1ecdb85b66dbee00debe934d16

**Comment by Lanayx** [comment]
@jkone27 no, it's impossible to generate OpenApi spec using reflection, since `EndpointHandler` doesn't have any information about input or output type (it's type is [`HttpContext -> Task`](https://github.com/Lanayx/Oxpecker/blob/develop/src/Oxpecker/Core.fs#L10)), that's why manual configuration is required (and then generation is based on reflection as you requested)

**Comment by Lanayx** [comment]
Closing as non-actionable
